### ISSUE TITLE
Error While Installing Dependencies with Maven

### ISSUE THREAD

**Issue by djokester** [FraBle/python-sutime#12]
I installed maven2 with 
`sudo apt-get install maven2`

Then I ran
`mvn dependency:copy-dependencies -DoutputDirectory=./jars
`
I got the following error

> [INFO] Scanning for projects...
> [INFO] Searching repository for plugin with prefix: 'dependency'.
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Maven Default Project
> [INFO]    task-segment: [dependency:copy-dependencies]
> [INFO] ------------------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [ERROR] BUILD ERROR
> [INFO] ------------------------------------------------------------------------
> [INFO] Cannot execute mojo: copy-dependencies. It requires a project with an existing pom.xml, but the build is not using one.
> [INFO] ------------------------------------------------------------------------
> [INFO] For more information, run Maven with the -e switch
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: < 1 second
> [INFO] Finished at: Mon May 07 20:06:56 IST 2018
> [INFO] Final Memory: 4M/118M
> [INFO] ------------------------------------------------------------------------
>

**Comment by AshwiniPatil5** [comment]
@djokester : I'm facing the same issue.. any update or were you able to resolve this?

**Comment by FraBle** [comment]
From what directory are you executing the command?

**Comment by AshwiniPatil5** [comment]
@FraBle : Thank you so much for the response. I could resolve it with 
copying pom.xml in the sutime directory path 
and then executing mvn dependency:copy-dependencies -DoutputDirectory=./jars.

But now I'm stuck with the another issue. 
sutime library is working all super fine in my local machine. 
But I need to use this in aws lambda. so trying to deploy it as a zip file. 
But the dependency =>stanford-corenlp-3.6.0-models.jar is 369~MB. 
But the aws lambda service has size limit of 262MB. 
So any guidance for using this in aws lambda would be of great help. 
and also if you can point to any other alternatives for python would also be of great help.!

**Comment by FraBle** [comment]
Unfortunately not, the Java library from Stanford is that huge, or rather the models 😞 
However, it looks like AWS increased their limits to 3008 MB: https://docs.aws.amazon.com/lambda/latest/dg/limits.html

**Comment by shandilya1998** [comment]
Hey! I trying to download the java dependencies and am not able to resolve this issue. Please help.
