### ISSUE TITLE
ReflectionLoadingException for funtion SUTime

### ISSUE THREAD

**Issue by rohitmujumdar** [FraBle/python-sutime#19]
STACK TRACE : 

edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingExceptionPyRaisableTraceback (most recent call last)
<ipython-input-2-4f8cff2ef710> in <module>()
      6 
      7 jar_files = "C:/Users/Rohit/AppData/Local/conda/conda/envs/rohitfroot/Lib/site-packages/sutime/jars"
----> 8 sutime = SUTime(jars=jar_files, mark_time_ranges=True)
      9 
     10 print(json.dumps(sutime.parse(test_case), sort_keys=True, indent=4))

~\AppData\Local\conda\conda\envs\rohitfroot\lib\site-packages\sutime\sutime.py in __init__(self, jars, jvm_started, mark_time_ranges, include_range)
     57                 'edu.stanford.nlp.python.SUTimeWrapper')
     58             self._sutime = SUTimeWrapper(
---> 59                 self.mark_time_ranges, self.include_range)
     60             self._is_loaded = True
     61         finally:

~\AppData\Local\conda\conda\envs\rohitfroot\lib\site-packages\jpype\_jclass.py in _javaInit(self, *args)
    109     else:
    110         self.__javaobject__ = self.__class__.__javaclass__.newClassInstance(
--> 111             *args)
    112 
    113 

edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingExceptionPyRaisable: edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl

DETAILS : 
Python == 3.7
OS == Windows 8.1
JPype == 0.6.3

Could anyone tell me what is going wrong?

**Comment by devmaha** [comment]
Getting same error with Python 3.6 too. It would be wonderful to get some help on this topic.

**Comment by FraBle** [comment]
Seems to be an issue with Java itself: https://github.com/stanfordnlp/CoreNLP/issues/636
I'm currently looking into upgrade the dependencies.

**Comment by FraBle** [comment]
Could you please install the [v.1.0.0 release candidate](https://pypi.org/project/sutime/1.0.0rc1/) with `pip install sutime==1.0.0rc1`, update the Java dependencies with `mvn dependency:copy-dependencies -DoutputDirectory=./jars`, and check if the error still comes up?

**Comment by rohitmujumdar** [comment]
Thank you. It works now. Loved the tool, it's very comprehensive.
