### ISSUE TITLE
Other language support?

### ISSUE THREAD

**Issue by chuan137** [FraBle/python-sutime#21]
Hi,

thanks fro the efforts. it's a really wonderful library. I am very new to NLP and have a simple question. I read from the CoreNLP page, there are several language supported, including German and Chinese. I am wondering if they are also supported by this package, since it is dependent on the CoreNLP.

Chuan

**Comment by FraBle** [comment]
I update the readme and code to cover your questions.
The gist is: (the original Java) SUTime only supports English, British, and Spanish ([Source](https://github.com/stanfordnlp/CoreNLP/tree/master/src/edu/stanford/nlp/time/rules)). You might be able to download the other language models, but Stanford's SUTime doesn't support them.
