### ISSUE TITLE
Can't use in other folder

### ISSUE THREAD

**Issue by letanloc1998** [FraBle/python-sutime#30]
I have a bug:
    site-packages/jpype/_jclass.py", line 212, in _JClassNew
        javaClass = _jpype.PyJPClass(arg)
    jpype._jclass.NoClassDefFoundError: edu/stanford/nlp/python/SUTimeWrapper

require is wrong (in package install)
    # _required_jars = {
    #     'stanford-corenlp-3.6.0-models.jar',
    #     'stanford-corenlp-3.6.0.jar',
    #     'gson-2.7.jar',
    #     'slf4j-simple-1.7.21.jar'
    # }
    _required_jars = {
        "stanford-corenlp-3.9.2-models.jar",
        "stanford-corenlp-3.9.2.jar",
        "gson-2.8.5.jar",
        "slf4j-simple-1.7.25.jar",
    }

**Comment by HWZX** [comment]
May I ask whether you have solve this problem?
Thank you.

**Comment by letanloc1998** [comment]
I fixed it. Change require because it updated

**Comment by HWZX** [comment]
Could you tell me where did you change? 
My error information is
jpype._jclass.NoClassDefFoundError: java.lang.NoClassDefFoundError: org/joda/time/ReadablePartial
I can't figure out where should I change the code.
Thank you.

**Comment by letanloc1998** [comment]
Use in this folder or change source

**Comment by arjun251** [comment]
I have updated my _required_jars. I am getting below error. Please help me to resolve this issue. below are my logs.

  File "/Users/arjunsadhu/Downloads/python-sutime-master/sutime/sutime.py", line 87, in __init__
    self._sutime = wrapper(mark_time_ranges, include_range, language)

java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: org/joda/time/ReadablePartial

**Comment by letanloc1998** [comment]
Sorry i can't help you with this problem. I think you missing lib
