### ISSUE TITLE
SUTimeWrapper not found

### ISSUE THREAD

**Issue by matthewrfellows** [FraBle/python-sutime#4]
After following the install instructions, and copying the example code into a file called core.py,
running `python core.py` results in the following error:

python2.7/site-packages/jpype/_jclass.py", line 55, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class edu.stanford.nlp.python.SUTimeWrapper not found

From what I can tell from the code, all the files are in the correct locations.
Any idea what might be wrong?

This is all running inside a virtualenv
on OSX El Cap 10.11.6
with Python version 2.7.9 (64 bit)
Java version: 
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by FraBle** [comment]
Hi Matthew,

First: try to reinstall the package: `pip install sutime -I`

I just created a new test project using Python 2.7.
The project structure is the following:
```
./jars
./pom.xml
./test.py
```

Inside `./jars` you will find:
```
ejml-0.23.jar
gson-2.7.jar
javax.json-api-1.0.jar
jaxb-api-2.2.7.jar
joda-time-2.9.jar
jollyday-0.4.7.jar
slf4j-api-1.7.12.jar
slf4j-simple-1.7.21.jar
stanford-corenlp-3.6.0-models.jar
stanford-corenlp-3.6.0.jar
xalan-2.7.0.jar
xercesImpl-2.8.0.jar
xml-apis-1.3.03.jar
xom-1.2.10.jar
```

Inside test.py is the following code:

```python
import os
import json
from sutime import SUTime

if __name__ == '__main__':
    test_case = u'I need a desk for tomorrow from 2pm to 3pm'

    jar_files = os.path.join(os.path.dirname(__file__), 'jars')
    sutime = SUTime(jars=jar_files, mark_time_ranges=True)

    print(json.dumps(sutime.parse(test_case), sort_keys=True, indent=4))
```

These are the installed dependencies from pip:
```
JPype1==0.6.2
sutime==0.2.0
wheel==0.24.0
```

With all these files I was able to run SUTime from python and get a result.
I hope this helps.

**Comment by matthewrfellows** [comment]
Thanks a lot for taking the time to respond.
Unfortunately, I'm still getting the same error.
Actually, I was getting another error, but after pip installing numpy I'm back to the SUTimeWrapper Class not found error.

I made a clean project directory, and set it up as you did, above. When I run `pip freeze`, I get:
appdirs==1.4.0
JPype1==0.6.2
numpy==1.12.0
packaging==16.8
pyparsing==2.1.10
six==1.10.0
sutime==0.2.0

For some reason this isn't quite what you have, above. Among other things, it's missing `wheel`. Not sure if that has anything to do with the problem. (wheel is actually installed in my venv, it's just not in that list).

**Comment by zjyin** [comment]
I also have the same issues. Is there something that we missed when installing the package? Thanks!

jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class edu.stanford.nlp.python.SUTimeWrapper not found

**Comment by FraBle** [comment]
That's a really odd issue.
The class should be shipped inside a jar with the package:
https://github.com/FraBle/python-sutime/blob/master/sutime/jars/stanford-corenlp-sutime-python-1.0.0.jar

I will look into this.

**Comment by FraBle** [comment]
@zjyin, @matthewrfellows, can you please check that the jar file is in your installed package?

**Comment by FraBle** [comment]
Do you maybe mix 64bit and 32bit of Python and JVM?
http://stackoverflow.com/a/23436235/1415532

**Comment by matthewrfellows** [comment]
Hi, yes, I saw the 64/32 bit incompatibility issue when I was originally searching for a solution. I made sure that both my Java and Python are 64 bit, which they are.
When I look at the files, it seems like everything is where it should be. I still have no idea what the problem is.
I had a similar issue with a different library (Python-Natty), but adding a manifest file and building it myself fixed it. This didn't help in the case of SUTime, sadly.

**Comment by FraBle** [comment]
That's really sad 😞 
I asked some of my colleagues to try to reproduce it.
I'm currently not able to test it further right now (I'm off for my wedding).
Starting from March I should be back on track.

**Comment by r-springer** [comment]
We were able to at least reproduce the bug now. The problem here was that there was still another JVM installed in addition to Java 8. JPype fetched the wrong JVM.
```python
>>> import jpype
>>> jpype.getDefaultJVMPath()
'/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/jli/libjli.dylib'
```

We resolved this by just deleting the wrong version. (`rm –rf /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk`) I don't know and haven't looked into whether there is another way to point JPype to the correct directory.

Hope this gets us closer to a solution.

**Comment by thenewcomer** [comment]
I also have the same issue. But following @r-springer 's solution, I have solved this problem.

**Comment by vivektys** [comment]
Was this ever resolved. I have 64 bit Java and 64 python and have exactly the specification FraBle had but still I am getting the same error. Is there a fix?

**Comment by sekharvth** [comment]
I'm getting the same error. I guess this still is an issue

**Comment by marikiya88** [comment]
Hi @FraBle I'm still having the same issue. I've already reinstalled the v.1.0.0. release candidate but still not working. Any ideas?

**Comment by AminR4** [comment]
Greetings @FraBle 

I have the same Issue:

name = 'edu.stanford.nlp.python.SUTimeWrapper'

    def JClass(name):
        jc = _jpype.findClass(name)
        if jc is None:
>           raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
E           jpype._jexception.java.lang.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class edu.stanford.nlp.python.SUTimeWrapper not found

../../../anaconda3/envs/sutimeTest/lib/python3.6/site-packages/jpype/_jclass.py:55: java.lang.RuntimeExceptionPyRaisable


**I have:** 

python 3.6.7

openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)

Ubuntu 18.0.4

wheel                     0.32.2
sutime                    1.0.0rc4
JPype1                    0.6.2

**My jar Files:**

activation-1.1.1.jar                lucene-core-4.10.3.jar
AppleJavaExtensions-1.4.jar         lucene-queries-4.10.3.jar
commons-lang3-3.3.1.jar             lucene-queryparser-4.10.3.jar
ejml-0.23.jar                       lucene-sandbox-4.10.3.jar
gson-2.8.5.jar                      protobuf-java-3.2.0.jar
javax.activation-api-1.2.0.jar      slf4j-api-1.7.12.jar
javax.json-1.0.4.jar                slf4j-simple-1.7.25.jar
javax.servlet-api-3.0.1.jar         stanford-corenlp-3.9.2.jar
jaxb-api-2.3.1.jar                  stanford-corenlp-3.9.2-models.jar
jaxb-core-2.3.0.1.jar               stanford-corenlp-3.9.2-models-spanish.jar
jaxb-impl-2.3.1.jar                 xalan-2.7.0.jar
joda-time-2.9.4.jar                 xercesImpl-2.8.0.jar
jollyday-0.4.9.jar                  xml-apis-1.3.03.jar
lucene-analyzers-common-4.10.3.jar  xom-1.2.10.jar

**And:**

There is only one alternative in link group java (providing /usr/bin/java): /usr/lib/jvm/java-11-openjdk-amd64/bin/java
Nothing to configure.

I have tried everything if you could help me in some way I would me gratefull.

Thank you so much for your work.

**Comment by AminR4** [comment]
So a new day a new mind i got a solution.

I have all the aforementioned configurations AND i installed the new java 11 using this guide:

https://websiteforstudents.com/how-to-install-oracle-java-jdk-11-on-ubuntu-18-04-16-04-18-10/

with the addition of a command:

sudo update-alternatives --set java /usr/lib/jvm/jdk-11.0.1/bin/java

set your alternative to be the new installed java and then check that maven is using the same jdk.

Then you are set to go.

**Comment by marikiya88** [comment]
Hi @FraBle I think I found my problem!

The issue was that, when running `python test.py` from the folder python-sutime, it was loading the sutime package that was included inside that folder; instead of the installation at python2.7/site-packages or whatsoever. I just created a test.py script outside the folder python-sutime, and passed the jar folder accordingly and everything worked out! 

I also had to match the versions of the required libraries in sutime.py to the downloaded files in the jar folder because they didn't agree (maybe because of all the updates that I've run afterwards).

**Comment by marikiya88** [comment]
Hi again @FraBle  I have the 0.2.0 version running ok, but since I'd like to run the spanish annotator, I'd like to use version 1.0.0. However, I'm facing the "SUTimeWrapper not found" error. 
I think something is going on with the 1.3.0 jar. If I change sutime.py code so that it uses 1.0.0 jar (and remove the `language` parameter in the call everything works out correctly); but it raises an error with the newer jar. Any ideas? I've checked I'm using jdk 1.8.

**Comment by cchristodoulaki** [comment]
I'm still having this problem?

I ran 
```
git clone https://github.com/FraBle/python-sutime.git
cd python-sutime
pip install sutime
mvn dependency:copy-dependencies -DoutputDirectory=./jars
nano test.py
```
I added the following to `nano.py`.
```
import os
import json
from sutime import SUTime

if __name__ == '__main__':
    test_case = u'I need a desk for tomorrow from 2pm to 3pm'

    jar_files = os.path.join(os.path.dirname(__file__), 'jars')
    sutime = SUTime(jars=jar_files, mark_time_ranges=True)

    print(json.dumps(sutime.parse(test_case), sort_keys=True, indent=4))
```

`python test.py `

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    sutime = SUTime(jars=jar_files, mark_time_ranges=True)
  File "/home/christina/gitrepos/python-sutime/sutime/sutime.py", line 68, in __init__
    SUTimeWrapper = jpype.JClass("edu.stanford.nlp.python.SUTimeWrapper")
  File "/home/christina/anaconda3/lib/python3.6/site-packages/jpype/_jclass.py", line 55, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class edu.stanford.nlp.python.SUTimeWrapper not found

**Comment by FraBle** [comment]
Hey everyone!
Please install the latest release candidate with `pip install sutime==1.0.0rc5` and try it out in your local environment.

I've recompiled the Java class `edu.stanford.nlp.python.SUTimeWrapper` and tested it locally with the following Java/JVM versions:
- `jdk1.8.0_202.jdk`
- `jdk-9.0.4.jdk`
- `jdk-10.0.2.jdk`
- `openjdk-11.jdk`
- `openjdk-12.jdk`

Any JDK >= 1.8 should be able to run `python-sutime`.
