### ISSUE TITLE
How to use sutime with CoreNLP-3.7.0

### ISSUE THREAD

**Issue by naka13** [FraBle/python-sutime#5]
Currently, sutime `sutime==0.2.0` doesn't seem to work with the latest version of CoreNLP(3.7.0).
Confirmed by `_required_jars` being set to jars for version 3.6.0.
Can I use the existing wrapper to work with the latest version of CoreNLP? If so, what changes I need to make.
If not, are there any plans for this integration.

**Comment by FraBle** [comment]
Hi @naka13, it should hopefully run without limitations.
I'm currently not able to test it right now (I'm off for my wedding).
If you want, you can test it and create a pull request.
Starting from March I should be back on track.

**Comment by FraBle** [comment]
Hi @naka13, in case you still want to try out SUTime with the latest version, please install the [v.1.0.0 release candidate 4](https://pypi.org/project/sutime/1.0.0rc4/) with `pip install sutime==1.0.0rc4` and update the Java dependencies with `mvn dependency:copy-dependencies -DoutputDirectory=./jars`.
It runs now with SUTime v3.9.2 (the current latest release).
